#Application Name -> http://localhost:8761/
spring:
  application:
    name: getaway-service     # This is the name for the remote configuration file
  config:
    import:
    - optional:configserver:http://localhost:8888